export const users = [
  {
    _id: '6731cb888d391ed5e68b33d9',
    index: 0,
    guid: 'ea63c927-f8cf-48dd-a925-ef0f88c33a10',
    isActive: false,
    balance: '$1,175.18',
    picture: 'http://placehold.it/32x32',
    age: 30,
    eyeColor: 'brown',
    name: 'Delgado Casey',
    gender: 'male',
    company: 'APPLIDEC',
    email: 'delgadocasey@applidec.com',
    phone: '+1 (819) 574-2264',
    address: '644 Forest Place, Shrewsbury, Alabama, 9294',
    about:
      'Magna incididunt nostrud id aliqua qui esse sint. Et amet et ut voluptate in non fugiat fugiat excepteur eiusmod ipsum est est. Incididunt sint veniam nulla minim reprehenderit proident proident. Do est irure enim non dolor eiusmod.\r\n',
    registered: '2016-12-01T10:47:45 -03:00',
    latitude: 30.962662,
    longitude: 1.996739,
    tags: [
      'veniam',
      'quis',
      'exercitation',
      'commodo',
      'irure',
      'elit',
      'veniam',
    ],
    friends: [
      {
        id: 0,
        name: 'Felicia Velazquez',
      },
      {
        id: 1,
        name: 'Rae Sykes',
      },
      {
        id: 2,
        name: 'Hart Daniel',
      },
    ],
    greeting: 'Hello, Delgado Casey! You have 4 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '6731cb88d50f127a9111f4e9',
    index: 1,
    guid: '6f1c4674-3161-4966-bf77-f4e385ea9a4a',
    isActive: false,
    balance: '$1,498.08',
    picture: 'http://placehold.it/32x32',
    age: 27,
    eyeColor: 'brown',
    name: 'Marcy Norton',
    gender: 'female',
    company: 'CUJO',
    email: 'marcynorton@cujo.com',
    phone: '+1 (924) 500-3920',
    address: '471 Eastern Parkway, Garnet, Oklahoma, 5656',
    about:
      'Cupidatat laborum eu reprehenderit qui qui. Nostrud mollit deserunt fugiat reprehenderit quis aliquip laboris nostrud irure. Cupidatat ex tempor do in dolore commodo in magna ea.\r\n',
    registered: '2015-06-07T05:56:04 -03:00',
    latitude: 56.919066,
    longitude: -107.899916,
    tags: ['est', 'dolore', 'reprehenderit', 'ipsum', 'commodo', 'elit', 'qui'],
    friends: [
      {
        id: 0,
        name: 'Verna Kirk',
      },
      {
        id: 1,
        name: 'Terrie Erickson',
      },
      {
        id: 2,
        name: 'Turner Gould',
      },
    ],
    greeting: 'Hello, Marcy Norton! You have 6 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6731cb88dc2da030b582c540',
    index: 2,
    guid: '5dda7025-b883-42bd-aac3-0f8a0cb1a0e2',
    isActive: false,
    balance: '$2,772.73',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'brown',
    name: 'Herring Carver',
    gender: 'male',
    company: 'NURPLEX',
    email: 'herringcarver@nurplex.com',
    phone: '+1 (995) 549-3478',
    address: '744 Visitation Place, Gilmore, American Samoa, 6171',
    about:
      'Sunt mollit ea quis ipsum laboris aute ipsum cillum occaecat consectetur. Id enim labore amet ad sint nostrud id labore aliquip. Sint laboris laborum duis id commodo ea ut reprehenderit amet. Elit voluptate dolor adipisicing incididunt laboris eiusmod. Veniam labore fugiat mollit nostrud exercitation ullamco veniam sit occaecat mollit. Deserunt laborum voluptate nisi culpa excepteur.\r\n',
    registered: '2015-04-01T06:05:25 -03:00',
    latitude: -85.026576,
    longitude: -34.219259,
    tags: [
      'id',
      'deserunt',
      'minim',
      'dolore',
      'cupidatat',
      'aliquip',
      'aliquip',
    ],
    friends: [
      {
        id: 0,
        name: 'Garrett Diaz',
      },
      {
        id: 1,
        name: 'Dillon Bentley',
      },
      {
        id: 2,
        name: 'Estes Briggs',
      },
    ],
    greeting: 'Hello, Herring Carver! You have 1 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6731cb882232c2dee59ce7fe',
    index: 3,
    guid: '258b5dc8-cf81-4024-9aca-279893374370',
    isActive: true,
    balance: '$1,337.27',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'brown',
    name: 'Simpson Gregory',
    gender: 'male',
    company: 'EURON',
    email: 'simpsongregory@euron.com',
    phone: '+1 (866) 590-2317',
    address: '138 Morton Street, Indio, Connecticut, 821',
    about:
      'Veniam labore incididunt duis aute id do nulla ut velit velit. Non laborum elit aliqua velit tempor. Id aliquip anim proident occaecat velit proident minim eu non officia nulla. Eu culpa consequat eu laborum.\r\n',
    registered: '2022-09-10T09:09:43 -03:00',
    latitude: -55.393081,
    longitude: 15.051675,
    tags: ['ea', 'eu', 'sit', 'pariatur', 'qui', 'nulla', 'in'],
    friends: [
      {
        id: 0,
        name: 'Ebony Michael',
      },
      {
        id: 1,
        name: 'Tamra Ellison',
      },
      {
        id: 2,
        name: 'Adriana Harding',
      },
    ],
    greeting: 'Hello, Simpson Gregory! You have 10 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '6731cb889fa6b8c3f2f8453f',
    index: 4,
    guid: 'e2825899-65bf-4f76-92c9-4af9371a187c',
    isActive: true,
    balance: '$3,495.35',
    picture: 'http://placehold.it/32x32',
    age: 24,
    eyeColor: 'blue',
    name: 'Dodson Carlson',
    gender: 'male',
    company: 'LEXICONDO',
    email: 'dodsoncarlson@lexicondo.com',
    phone: '+1 (947) 560-2598',
    address: '810 Lombardy Street, Cartwright, Maine, 1943',
    about:
      'Consectetur velit sunt irure id do. Eiusmod sit proident magna aute culpa adipisicing quis fugiat excepteur pariatur proident ullamco proident. Sunt aliquip aute consequat consectetur est ullamco non deserunt commodo magna. Et ipsum non incididunt ex duis mollit deserunt culpa ullamco laborum magna nostrud. Laborum sint nulla cupidatat aute aliquip aute exercitation cillum do cupidatat occaecat velit voluptate.\r\n',
    registered: '2018-03-22T01:25:17 -03:00',
    latitude: 71.569072,
    longitude: 127.013899,
    tags: ['enim', 'esse', 'magna', 'esse', 'irure', 'sint', 'sit'],
    friends: [
      {
        id: 0,
        name: 'Heath Pope',
      },
      {
        id: 1,
        name: 'Jane Fitzgerald',
      },
      {
        id: 2,
        name: 'Wagner Swanson',
      },
    ],
    greeting: 'Hello, Dodson Carlson! You have 6 unread messages.',
    favoriteFruit: 'banana',
  },
];
